# Generated by Django 5.1 on 2024-09-19 14:05

import otp.models.otp_model
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginOtp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=256, verbose_name='code')),
                ('attempts', models.IntegerField(default=0, verbose_name='attempts')),
                ('max_attempts', models.IntegerField(default=3, verbose_name='max attempts')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified')),
                ('expires_at', models.DateTimeField(default=otp.models.otp_model.get_default_expires_at, verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_attempted', models.DateTimeField(auto_now=True, verbose_name='last attempted')),
            ],
            options={
                'verbose_name': 'login OTP code',
                'verbose_name_plural': 'login OTP codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
