# Generated by Django 5.1 on 2024-09-16 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loginotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_otp_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='panel.category'),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='panel.product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'slug', 'is_active'], name='panel_produ_name_2f1087_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['product', 'is_active', 'created_at'], name='panel_price_product_5a4be6_idx'),
        ),
    ]
