# Generated by Django 5.1 on 2024-09-02 09:46

import django.db.models.deletion
import shop.models.category_model
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='discount percentage')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
                ('icon', models.ImageField(blank=True, upload_to=shop.models.category_model.category_icon_upload_to, verbose_name='icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'slug', 'is_active'], name='shop_catego_name_8f9a1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='shop.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='shop.discount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='shop.product')),
            ],
            options={
                'verbose_name': 'price',
                'verbose_name_plural': 'prices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'slug', 'is_active'], name='shop_produc_name_731dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['amount', 'is_active', 'created_at'], name='shop_price_amount_91b116_idx'),
        ),
    ]
