# Generated by Django 5.1 on 2024-09-02 09:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_price_remove_product_shop_produc_name_a2070e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='discount percentage')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='shop.discount'),
        ),
    ]
